<?php

$title = 'Add songs';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('chanson',
    array(
        'action' => 'add',
        'id'     => $id_album,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('id_album'));
echo $this->formRow($form->get('titre'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
