<?php

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Nb songs</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php $i=0;
    foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td><?php echo $this->escapeHtml($nbchansons[$album->id]);?></td>
            <td> <a href="<?php echo $this->url('chanson',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit songs</a> </td>
            <td> <a href="<?php echo $this->url('chanson',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete songs</a> </td>
            <td>  <a href="<?php echo $this->url('chanson',
                    array('action'=>'display', 'id' => $album->id));?>">Display songs</a> </td>
        </tr>
    <?php endforeach; ?>
</table>