<?php

$title = 'Inscription';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<fieldset>
    <legend> Inscription </legend>
    <table>
        <?php echo $this->form()->openTag($form);?>
        <?php foreach($form->getElements() as $element) {
          //  echo '<tr><td>'.PHP_EOL;
            echo $this->formRow($element);
            echo '<br>'.PHP_EOL;
        }
         echo $this->form()->closeTag($form);
        ?>
    </table>
</fieldset>